UploadV2 Backend
uraisg/media-library-azure pull request #117
Opened 2022-09-23 01:02 UTC by Rin-chan

2022-09-23 08:19 UTC, Rin-chan commented
[IgnoreAntiforgeryToken] Should be removed in DraftController. However I can't seem to run it with this removed.

2022-09-27 08:14 UTC, Rin-chan commented
> [IgnoreAntiforgeryToken] Should be removed in DraftController. However I can't seem to run it with this removed.

Fixed

2022-10-05 09:01 UTC, khteo requested changes

2022-10-05 09:01 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/ImageInput.js
> +        acceptedFileTypes={['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'image/bmp', 'image/heic']}
Suggest to retest the upload behaviour on mobile browsers now that we are no longer using an vanilla <input> tag. Does iOS still sanitise the HEIC files and re-compress to JPEG?

2022-10-05 09:44 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/Background/ScheduledService.cs
> +        private static readonly string Schedule = "*/2 * * * *";
Changed to "59 23 * * *"

2022-10-05 09:44 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/Controllers/DraftController.cs
> +            return;
Removed

2022-10-05 09:45 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
> +
Removed

2022-10-05 09:45 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/AllContext.js
> +  ])
Removed

2022-10-05 09:45 UTC, Rin-chan commented on internet-webapp/package.json
> +{
Removed

2022-10-06 02:46 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/PreviewUpdate.js
> +    }, 1000)
Removed most of the setTimeout except for "setTimeout(() => { formContext.setAlertActive(false) }, 5000)" in Stepper.js as this displays the alert to tell user that the file has been uploaded into intranet.

2022-10-06 03:45 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/Controllers/DraftController.cs
> +        }
Done

2022-10-06 03:46 UTC, Rin-chan commented on internet-webapp/MediaLibrary.Internet.Web/AppSettings.cs
> +        public string MediaStorageConnectionStringImage { get; set; }
MediaStorageConnectionStringImage uses the same string from MediaStorageConnectionString in Intranet

2022-10-06 04:15 UTC, khteo approved these changes
+1

2022-10-06 06:23 UTC, merged