declaration checkbox codes
uraisg/media-library-azure pull request #414
Opened 2023-05-02 07:14 UTC by ivyyy13

declaration checkbox

2023-05-05 02:55 UTC, khteo requested changes

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
> +      })
Remove `console.log` statement use for debugging. Indentation also seems a bit off.

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
> +                    //the logger here also need to remove
??

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
> +                DeclarationCheckbox = json.DeclarationCheckbox.ToString()
What is the reason for casting to String? Any issues with keeping it as a bool?

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Api/ImageEntity.cs
> +        public string DeclarationCheckbox { get; set; }
The name `DeclarationCheckbox` is not very intuitive. Change to something more self-explanatory, like `DeclaredClassification`.

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
> +        private static async Task IndexUploadToTable (ImageEntity json, AppSettings appSettings)
style: extra whitespace

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
> +					<img class="img-fluid pt-3 w-75 " src="~/images/qrcode.png">
Accessibility: Suggest to either set `aria-hidden="true"` or `alt=""` since QR codes are not useful for screen readers.

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/PreviewUpdate.js
> +  //try
??

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/AllContext.js
> +  const [declarationcheckbox, setdeclarationcheckbox] = useState(false)
style: use camelCase for js variable names

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/PreviewUpdate.js
> +      <div className="d-flex align-items-center shadow-sm p-3 mb-4 rounded" style={{ backgroundColor: "#f5f5f5", width: "1100px", height: "50px" }}>
Container should be a percentage of column width (e.g., 90%, 100%), is having a fixed height necessary? How does it reflow on narrow screens?

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
> +        uploadStep2()
Explain why `uploadStep2` is called when declaration is not done.

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
> +          console.log("hiii")
??

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
> +            console.log(response)
??

2023-05-05 02:55 UTC, khteo commented on internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
> +          console.log(formContext.declarationcheckbox)
?

2023-05-05 02:55 UTC, khteo commented on intranet-webapp/MediaLibrary.Intranet.Web/Models/InternetIndexModel.cs
> +        public string declarationCheckbox { get; set; }
Same concern on variable name as above, and consider representing as a `bool`

2023-05-08 03:33 UTC, ivyyy13 commented
<img width="946" alt="image" src="https://user-images.githubusercontent.com/96662899/236727606-5cd31f84-4c3b-4599-95fc-0f11efd0300b.png">

<img width="944" alt="internetlandingpage" src="https://user-images.githubusercontent.com/96662899/236727650-35e31ab1-0ab4-4e93-8430-071f34cf4e23.png">

**Error prompt**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/96662899/236727791-b1c2e8ff-8226-4b37-9b3d-ef60a79fd03b.png">

2023-07-26 02:20 UTC, khteo approved these changes
Tested ok, thanks!

2023-07-26 02:21 UTC, merged